Issue 12 make outPath accept both str and Path
OceanNetworksCanada/api-python-client pull request #20
Opened 2023-12-20 05:05 UTC by Renfu-Li

Fixes https://github.com/OceanNetworksCanada/api-python-client/issues/12

Changed the type of outPath to str | Path and the way it was used in other methods and testings. This can facilitate testing and make the code cleaner by eliminating the need for sanitizing "outPath".

I also modified the `README.md` in `/tests` to reflect the directory structure change.

2023-12-20 23:41 UTC, kan-fu requested changes

2023-12-20 23:41 UTC, kan-fu commented on src/onc/onc.py
> +        @filename: if present, creates a file with a ".json" extension
Nice to catch the bug. It makes sense for the filename to be relative to the outPath.

2023-12-20 23:43 UTC, kan-fu commented
I have merged a quick workaround #22 for the problem that the PR from fork cannot use Actions secrets.

2023-12-20 23:49 UTC, Renfu-Li commented on tests/README.md
>  robot tests/suites/01*    # robot tests/suites/0X*
Sure, happy to update them

2023-12-21 00:07 UTC, Renfu-Li commented on tests/robot/libraries/delivery.py
> -    onc.outPath = outPath
Does this mean that I can make the changes and commit again in this PR, or should I wait for the decision of internal meeting on migrating to snake case?

2023-12-21 00:10 UTC, kan-fu commented on tests/robot/libraries/delivery.py
> -    onc.outPath = outPath
You can make the change for now. I can always revert the change if the meeting result is not in favor of snake case.

2023-12-21 00:13 UTC, Renfu-Li commented on tests/robot/libraries/delivery.py
> -    onc.outPath = outPath
Thanks for the explanation, I will make the changes and commit again to this branch.

2023-12-21 16:27 UTC, Jacob-Stevens-Haas commented on tests/robot/libraries/delivery.py
> -    onc.outPath = outPath
This is a common feeling for emigres from Java.

It's common in Python to allow users to set instance attributes directly, especially for something like an `ONC.outPath`.  The name clearly tells what the effects of modifying it does.  Moreover, the `ONC` object doesn't mutate on its own and basically just stores `__init__` arguments as common arguments for repeated API calls.  But if you need to protect an attribute, there's several ways:
* begin with a leading underscore, eg. `ONC._out_path` to show that it's not part of the public API
* Name mangling w/two underscores: `ONC.__out_path` which, when instantiated as `my_onc=ONC()`, becomes `my_onc.__ONC_out_path`.  This is primarily used by a superclass to control overloading - not this use case.
* `@property` decorators, which can either generate a `set_x` method automatically or prohibit them.  This is more what you're looking for.

If you want this function to modify `outPath` _but only during this function's execution_, you could instead use a context manager to store the old value and temporarily set it as a new value.

Regardless, the longer term solution might simply be to make `ONC` a `TypedDict` or `dataclass`, which would get rid of all the wrappers like
```
    def getDeviceCategories(self, filters: dict = None):
        return self.discovery.getDeviceCategories(filters)
```

2023-12-21 16:42 UTC, Jacob-Stevens-Haas reviewed
LGTM, with two suggestions!  There's also some theorycraft in whether to allow attribute access (common in python, guarded in Java).  Happy with whatever you guys choose, but I'm going to be out over the holidays, so don't let me hold you up.

2023-12-21 16:42 UTC, Jacob-Stevens-Haas commented on src/onc/onc.py
> +        self._out_path = Path(_out_path)
Would it make sense to fully resolve it as `Path(_out_path).resolve()` or `Path(_out_path).absolute()`?  That way all error messages utilizing `_out_path` will be clearer, and any user changing the working directory after instantiating an `ONC()` won't silently change their `_out_path` to append the new working directory.

2023-12-21 16:42 UTC, Jacob-Stevens-Haas commented on src/onc/onc.py
> +        @filename: if present, creates a file with a ".json" extension
Do... we really need this function?  It isn't used internally, and a generic helper function for dumping a dictionary to a file doesn't seem specific to ONC.  Removing it might just help make the code clearer and decrease maintenance.

2023-12-22 03:14 UTC, kan-fu commented on src/onc/modules/_util.py
> +        raise FileExistsError(str(filePath))
Could you change this to `raise FileExistsError(filePath.resolve())` as Jacob suggested? The str cast seems unnecessary

2023-12-22 03:16 UTC, kan-fu commented on src/onc/onc.py
> +        self._out_path = Path(_out_path)
It is a good idea to fully resolve it when printing error messages. But other that, I think `self._out_path` should work fine without resolving itself.

2023-12-22 03:17 UTC, kan-fu commented on src/onc/onc.py
> +        @filename: if present, creates a file with a ".json" extension
I totally agree with you. If it is a brand new project, I would not hesitate to remove it, or at least put it in  `onc.util.py`. But unlike the legacy broken files I deleted before, these methods are all working functions and might already be used by end users (especially `onc.print`, since it is mentioned in the [Getting Started](https://wiki.oceannetworks.ca/display/O2A/Getting+Started) doc). 

For now I am trying to not break any existing code and keep backwards compatibility.

2023-12-22 03:18 UTC, kan-fu commented on tests/robot/libraries/delivery.py
> -    onc.outPath = outPath
Thanks for mentioning these options! I think `@property` is exactly what I want. It even won't break the existing code if we name the setter `outPath` when internally we still use `self._out_path`. 

I think it is a legitimate requirement for users to change the `_out_path`, no matter by a setter method, or a direct assignment, and users should not bother the internal implementation. What I concern is not using encapsulation from a developer's perspective, as this might hinder code refactor, as in this case we are improving code quality but breaking existing code if users manually set self._out_path to string type instead of Path. `@property` seems a really pythonic way to solve it.

2023-12-22 04:02 UTC, kan-fu commented
> LGTM, with two suggestions! There's also some theorycraft in whether to allow attribute access (common in python, guarded in Java). Happy with whatever you guys choose, but I'm going to be out over the holidays, so don't let me hold you up.

We will also be off next week so there won't be any PR fom us. Happy holidays!

2023-12-22 16:23 UTC, Renfu-Li commented on src/onc/modules/_util.py
> +        raise FileExistsError(str(filePath))
Sure, I will modify it as suggested

2023-12-22 18:10 UTC, Renfu-Li commented
> LGTM, with two suggestions! There's also some theorycraft in whether to allow attribute access (common in python, guarded in Java). Happy with whatever you guys choose, but I'm going to be out over the holidays, so don't let me hold you up.

Thanks for your helpful suggestions. Have a great holiday!

2023-12-22 18:16 UTC, Renfu-Li commented on tests/robot/libraries/delivery.py
> -    onc.outPath = outPath
Thanks for your advices, I am going to modify the code to use `@property` instead.

2024-01-02 12:19 UTC, Jacob-Stevens-Haas commented on src/onc/onc.py
> +        self._out_path = Path(_out_path)
I meant more for error messages that we don't anticipate, rather than just the ones we raise.

But I guess the real question is, once instantiated/`_out_path` is set, should an ONC object always point to the same location?  In other words, do we expect users who want different downloads in different locations to change their working directory between downloads (we should not resolve), or do we want them to instantiate a new `ONC` object/use the setter function (we should resolve)?

2024-01-02 20:10 UTC, kan-fu commented on src/onc/onc.py
> +        self._out_path = Path(_out_path)
That is a good question. Different users might adopt different styles, and it should all be fine as long as the code is working properly.

But to me, the design of `onc` class seems to encourage a singleton pattern because I don't see any benefit of creating multiple objects. I think it is common to change the working directory between downloads to make the download folder more organized (for example grouped by some parameters like `locationCode`). So I would expect the user to only have one `onc` object, and change the `_out_path` when needed, as illustrated in the [code example](https://wiki.oceannetworks.ca/display/O2A/Internal+Use+Case). After this PR is merged, the previous code example still works, and the `_out_path` will be changed in an encapsulated (setter) way due to `@property` decorator.

So it seems it should fall into the "we should resolve" category. Could you add `resolve` at line 33, 52, and revert the change in _util.py? @Renfu-Li

2024-01-02 21:32 UTC, Renfu-Li commented on src/onc/onc.py
> +        self._out_path = Path(_out_path)
I see. I am going to resolve it as `Path(_out_path).resolve()` for cleaner error messages

2024-01-03 03:01 UTC, kan-fu approved these changes

2024-01-03 15:13 UTC, Jacob-Stevens-Haas commented on src/onc/onc.py
> +        self._out_path = Path(_out_path)
@kan-fu if you're interested, here's my two favorite resources on object-oriented design in python.  Not sure if you've seen them, but they might be insightful if you're coming from Java: [Stop Writing Classes](https://www.youtube.com/watch?v=o9pEzgHorH0), a PyCon 2012 talk, and python-patterns.guide, a website by frequent pycon contributor Brandon Rhodes.  Here's his blog on the [singleton pattern in Python](https://python-patterns.guide/gang-of-four/singleton/).

2024-01-03 18:43 UTC, kan-fu commented on src/onc/onc.py
> +        self._out_path = Path(_out_path)
Thanks! Indeed all my oop understanding comes from Java. I will take a look.

2024-01-05 18:49 UTC, eliferguson approved these changes

2024-01-05 18:54 UTC, merged